### PR TITLE
Disable background image when high contrast is enabled

### PR DESCRIPTION
**Pull request by ghost**
fixes https://github.com/AyatanaIndicators/ayatana-indicator-a11y/issues/28.

### CODE REVIEW

**Review by sunweaver — APPROVED** [review]
LGTM

**Comment by sunweaver** [comment]
As a side note: it would be nice to make the background color in high contrast mode configurable, as well. Or derive it from the high contrast theme (inverse -> black background, non-inverse -> white background).

**Comment by sunweaver** [comment]
@tari01 Please file the above as a bug if needed.

**Comment by tari01** [comment]
> @tari01 Please file the above as a bug if needed.



> As a side note: it would be nice to make the background color in high contrast mode configurable, as well. Or derive it from the high contrast theme (inverse -> black background, non-inverse -> white background).

Already planned as part of the fix to https://github.com/AyatanaIndicators/ayatana-indicator-a11y/issues/29.

**Pull request merged**
